
-- -- 5. Grace Ackon (Form 5)
-- -- Note: Last name was blank on form; Ackon appears to be middle/other name
-- (
--     gen_random_uuid(),
--     '1777703f-d720-48e5-9543-eba8d27e6a15',
--     'CACI-GH-ASSAK-00015',
--     'Grace',
--     'Ackon',
--     null,
--     null,
--     'female',
--     'married',
--     null,
--     null,
--     null,
--     null,
--     null,
--     'Assakae',
--     null,
--     null,
--     null,
--     'active',
--     null,
--     true,
--     NOW(),
--     NOW()
-- ),



-- -- 8. Juliana Oboye (Form 8)
-- (
--     gen_random_uuid(),
--     '1777703f-d720-48e5-9543-eba8d27e6a15',
--     'CACI-GH-ASSAK-00018',
--     'Juliana',
--     'Obboye',
--     null,
--     null,
--     'female',
--     null,
--     'Farming',
--     null,
--     null,
--     null,
--     null,
--     'Western Region',
--     'Christina Bossman',
--     '+233242833301',
--     'Other',
--     'active',
--     null,
--     true,
--     NOW(),
--     NOW()
-- ),



-- -- 36. Hannah Peasah (Form 6)
-- -- Note: No phone number on form. Branch field crossed out; "Mpohoor" written beside Takoradi.
-- -- Physical address: No. 33/1, Assakae, Western Region.
-- -- Join date: 2002-05-07. Emergency contact section has only a signature; name/phone null.
-- (
--     gen_random_uuid(),
--     '1777703f-d720-48e5-9543-eba8d27e6a15',
--     'CACI-GH-ASSAK-00046',
--     'Hannah',
--     'Peasah',
--     null,
--     '1980-04-14',
--     'female',
--     'married',
--     'Hair Dresser',
--     null,
--     null,
--     null,
--     null,
--     'No. 33/1, Assakae, Western Region',
--     null,
--     null,
--     null,
--     'active',
--     '2002-05-07',
--     true,
--     NOW(),
--     NOW()
-- ),


-- -- 39. Cecilia Akon (Form 9)
-- -- Note: Form is almost entirely blank. Only name, gender (female), and marital status (married) filled.
-- -- No phone, DOB, occupation, address, or emergency contact.
-- (
--     gen_random_uuid(),
--     '1777703f-d720-48e5-9543-eba8d27e6a15',
--     'CACI-GH-ASSAK-00049',
--     'Cecilia',
--     'Akon',
--     null,
--     null,
--     'female',
--     'married',
--     null,
--     null,
--     null,
--     null,
--     null,
--     null,
--     null,
--     null,
--     null,
--     'active',
--     null,
--     true,
--     NOW(),
--     NOW()
-- ),

